service: okta-pasword-migration-sidecar

custom:
  snsTopic: "${self:service}-${self:provider.stage}-importPassword"
  snsTopicArn:
    local:
      "arn:aws:sns:us-east-1:123456789012:${self:custom.snsTopic}"
    dev:
      { "Fn::Join" : ["", ["arn:aws:sns:${self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":${self:custom.snsTopic}" ] ]  }
    prod:
     { "Fn::Join" : ["", ["arn:aws:sns:${self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":${self:custom.snsTopic}" ] ]  }

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource: { "Fn::Join" : ["", ["arn:aws:sns:${self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":${self:custom.snsTopic}" ] ]  }
  environment:
    TENANT: ${file(./config.${opt:stage, self:provider.stage, 'dev'}.json):tenant}
    API_TOKEN: ${file(./config.${opt:stage, self:provider.stage,'dev'}.json):api_secret}
    FIXED_AUTH_SECRET: ${file(./config.${opt:stage, self:provider.stage,'dev'}.json):fixed_auth_secret}
    CLIENT_ID: ${file(./config.${opt:stage, self:provider.stage,'dev'}.json):client_id}
    CLIENT_SECRET_JWT: ${file(./config.${opt:stage, self:provider.stage,'dev'}.json):client_secret_jwt}

functions:
  #Authorizers
  auth:
    handler: src/authorizer/handler.fixed

  # Handle the password import inline hook
  verifyPassword:
    handler: src/verifyPassword.handler
    events:
      - http:
          path: /verify
          method: post
          authorizer:
            name: auth
            identitySource: method.request.header.Authorization

  # Handle import password event hook
  importPwordEventHookVerify:
    handler: src/importPasswordEventHook.verify
    events:
      - http:
          path: /complete
          method: get

  importPwordEventHook:
    handler: src/importPasswordEventHook.handler
    events:
      - http:
          path: /complete
          method: post
          authorizer:
            name: auth
            identitySource: method.request.header.Authorization
    environment:
      SnsTopicArn: ${self:custom.snsTopicArn.${self:provider.stage}}
      region: ${self:provider.region}

  importPwordEvent:
    handler: src/importPasswordEventHook.process
    events:
      - sns: ${self:custom.snsTopic}