service: okta-pasword-migration-sidecar

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  environment:
    TENANT: ${file(./config.${opt:stage, self:provider.stage, 'dev'}.json):tenant}
    API_TOKEN: ${file(./config.${opt:stage, self:provider.stage,'dev'}.json):api_secret}
    FIXED_AUTH_SECRET: ${file(./config.${opt:stage, self:provider.stage,'dev'}.json):fixed_auth_secret}
    CLIENT_ID: ${file(./config.${opt:stage, self:provider.stage,'dev'}.json):client_id}
    CLIENT_SECRET_JWT: ${file(./config.${opt:stage, self:provider.stage,'dev'}.json):client_secret_jwt}

functions:
  #Authorizers
  auth:
    handler: authorizer/handler.fixed

  #Dummy API
  public:
    handler: password-migration.perform
    events:
      - http:
          path: /
          method: post
          authorizer:
            name: auth
            identitySource: method.request.header.Authorization